import Head from 'next/head';
import Link from 'next/link';
import Newsletter from '@/components/Newsletter';
import PerfectBanner from '@/components/PerfectBanner';

export default function Home() {
    return (
        <>
            <Head>
                <title>Demo shop</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='frontLogo'>
                <div className='baner'>
                    <span className='tagLine'>
                        Luxury macarons made by hand
                    </span>
                    <Link className='shop-now' href='/shop'>
                        Shop now
                    </Link>
                </div>
            </div>

            <div className='intro'>
                <p>
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout.
                </p>
                <p>
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout.
                </p>
                <p>
                    It is a long established fact that a reader will be
                    distracted by the readable content of a page when looking at
                    its layout.
                </p>
            </div>
            <PerfectBanner />
            <Newsletter />
        </>
    );
}
